# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8bc143460a30ac49019b99f9f54583ef769ed2bcc500511f0c78ea96d751500761186855ac73b788fc6bcc51111cf9eaf3e4a69a89181cd4695a802786e48f5

test:
  secret_key_base: 8a012c7748943d2a01a8c6bbc6250bbb4f47cfe78c79b59ce9024a21a720adb4f5ed2dce18dac0e31743464272d0a67e6dca82a9125d972395d484f7a98f80e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
